{
 "title": "Postgresql_Instance_Health",
 "description": "Postgresql_Instance_Health",
 "tags": [ "example" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "⚠️ WAL Files Archive Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "(100 * sum by (server) (rate(pg_stat_archiver_failed_count[5m])) / sum by (server) (rate(pg_stat_archiver_archived_count[5m]) + rate(pg_stat_archiver_failed_count[5m])))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "% Requested Checkpoints vs Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_checkpoints_req[5m]) / ((rate(pg_stat_bgwriter_checkpoints_req[5m]) + rate(pg_stat_bgwriter_checkpoints_timed[5m])) > 0)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Checkpoint time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_checkpoint_sync_time[5m])",
     "legendFormat": "{{ handler }}"
    },
    {
     "expr": "rate(pg_stat_bgwriter_checkpoint_write_time[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Backend Buffer Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "100 * sum by (server) (rate(pg_stat_bgwriter_buffers_backend[5m])) / sum by (server) (rate(pg_stat_bgwriter_buffers_backend[5m]) + rate(pg_stat_bgwriter_buffers_checkpoint[5m]) + rate(pg_stat_bgwriter_buffers_clean[5m]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "⚠️ Background Writer Stops for Max Write Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_maxwritten_clean[5m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Buffers Allocated",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_buffers_oc[5m]) ",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Max Active Transaction Time by DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(15,(max by (datname,server)(pg_stat_activity_max_tx_duration{datname!~'template.*'})))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Connections Usage Percentage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "100 * sum(pg_stat_activity_count) by (server) / ((sum(pg_settings_max_connections) by (server)) - sum(pg_settings_superuser_reserved_connections) by (server))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "(sum(pg_settings_max_connections) by (server) - sum(pg_settings_superuser_reserved_connections) by (server)) - sum(pg_stat_activity_count) by (server) ",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "DBs Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "pg_database_size_bytes ", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Replication Lag (if replication)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "pg_replication_lag or vector(0)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "AVG Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "100 * avg by (server)(rate(pg_stat_database_blks_hit{datname!=''}[5m]) /((rate(pg_stat_database_blks_hit{datname!=''}[5m]) +rate(pg_stat_database_blks_read{datname!=''}[5m]))>0))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "# Servers UP",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "count(pg_up==1)", "legendFormat": "{{ handler }}" }
   ]
  },
  {
   "title": "Min. Postmaster Uptime",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "time() - max((pg_postmaster_start_time_seconds))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Max. Replication Lag",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max((pg_replication_lag)) or vector(0)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "text",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "options": {
    "content": "\n✅ Check that you have **up and running** as many servers as there should be in the current scope.  \n\n✅ Check that the minimum **postmaster service uptime** reflects the last known controlled restart of the servers in the current scope. If this is lower, it means that a server has been restarted for unknown reasons. \n\n✅ If you have replicated servers, check that the **replication lag is not too high**. This can lead to coherence problems if the master goes down. \n\n⭐️ **Tip**: Filter by cluster, namespace, and database to narrow down the result and identify the server with problems. "
   }
  },
  {
   "title": "Availability (2)",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "options": {
    "content": "🚩 Running **out of disk** is a general problem in databases.\n\n* ✅ Check that the node or could instance has **enough free disk**.\n * 👉 If your PostgreSQL is running in a Kubernetes node, check the Node Status & Overview dashboard\n * 👉 If your PostgreSQL is running in a RDS instance, check the AWS RDS dashboard\n\n🚩 Running out of disk can also cause the **Write Ahead Log (WAL) not to be able to write to disk**.\n"
   }
  },
  {
   "title": "Availability (3)",
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "options": {
    "content": "In databases CPU and memory are usually correlated.\n\n🚩 When a server runs out of memory can lead to more CPU load. There are some indicators that the memory is not used optimally in a server\n\n* ✅ Check that the **hit rate of the databases is not degraded**. The less the hit rate, the more consults the server has to make to the disk and more CPU load.\n\n* ✅ Check that there are not **too many requested checkpoints**. This means that the database has a buffer size smaller than it should. \n* ✅ Check also that there are not too many buffers allocated. Too many buffers can lead to **reaching the max write buffer**.  \n  *  👉  Before modifying the buffer size, check that there is enough free memory in the server. \n\nTo check the CPU and Memory available in your instance:\n * 👉 If your PostgreSQL is running in a Kubernetes node, check the Pod Status & Overview  dashboard\n * 👉 If your PostgreSQL is running in a RDS instance, check the AWS RDS dashboard\n"
   }
  },
  {
   "title": "Availability (4)",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "options": {
    "content": "🚩 Your server can be not available for a **connectivity problem in the could instance**\n* ✅  Check that the network throughput of your instance is over zero.\n\nTo check the network traffic of your instance:\n * 👉 If your PostgreSQL is running in a Kubernetes node, check the Node Status & Overview dashboard\n * 👉 If your PostgreSQL is running in an RDS instance, check the AWS RDS dashboard\n\n🚩 One of the possible error causes in PostgreSQL is **reaching the max. possible connections of the server**\n* ✅ Check that the server has **available connections**. \n  *  👉  Before modifying the maximum possible connections, check that there is enough free memory in the server. Each connected client needs memory available.\n"
   }
  },
  { "title": "Availability (5)", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Availability" } },
  { "title": "Availability (6)", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 }, "options": { "content": "# Storage" } },
  { "title": "Availability (7)", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 }, "options": { "content": "# Performance" } },
  { "title": "Availability (8)", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 41 }, "options": { "content": "# Network" } }
 ]
}