{
 "title": "Postgres Metrics",
 "time": { "from": "2023-10-08T18:43:16.740Z", "to": "2023-10-08T18:53:16.740Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Sessions States",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select state, count(*)\nfrom pg_stat_activity\nwhere state is not null\ngroup by state;"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT relname AS \"Table Name\", \n    n_tup_ins AS \"Insertion Count\",\n    n_tup_upd AS \"Updation Count\",\n    n_tup_del AS \"Deletion Count\"\nFROM pg_stat_user_tables\nWHERE schemaname = 'public';"
    }
   ]
  },
  {
   "title": "Table Size in KB",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n  table_name,\n  pg_relation_size(quote_ident(table_name)) / 1024 as \"Size in KB\"\nfrom information_schema.tables\nwhere table_schema = 'public'\norder by 2 desc;"
    }
   ]
  }
 ]
}